### ISSUE TITLE
Watchdog check

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#58]
As reported in email therad: **_Cron <root@sr-vm382-sitgwc> /var/lib/geowebcache/bin/watchdog.sh ---> invio ripetuto di mail di segnalazione_**

Below the email content:

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/73dd59ae-8ad9-48ba-8f9d-e17c6a9241fa)

**Comment by lpasquali** [comment]
@randomorder @tdipisa since I had to do the masters and document installation I fixed these 3 cronjobs

**Comment by tdipisa** [comment]
@lpasquali thank yo, but I see the issue still in Backlog/Tobia column. @randomorder @lpasquali please keep the kanbanboard updated at least in the Devops workspace otherwise it is difficult for me to keep track of the work.
